name: selfrdb
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip>=24.0
  - numpy>=1.23
  - scipy>=1.10
  - pyyaml>=6.0
  - pillow>=9.5
  - tqdm>=4.66
  - h5py>=3.8
  - scikit-image>=0.21
  - matplotlib>=3.7
  - psutil>=5.9
  - typing_extensions>=4.7
  # PyTorch will be installed via pip with platform markers in requirements.txt
  - pip:
      - -r requirements.txt